---
- name: Setup and Run Scrapers
  hosts: all
  become: yes
  vars:
    category: "{{ lookup('env', 'CATEGORY') }}"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600 # Cache valid for 1 hour to avoid updating each time

    - name: Install system dependencies
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - python3
          - python3-pip
          - locales
      retries: 5
      delay: 10
      until: result is succeeded
      register: result

    - name: Install Python packages
      pip:
        name: "{{ item }}"
      with_items:
        - scrapy
        - requests_cache
        - ipython
        - selenium
        - webdriver-manager
        - psycopg2-binary

    - name: Install Google Chrome
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

    - name: Clone repository
      git:
        repo: 'https://github.com/jorgeiras/buscainstrumentos_scrapers.git'
        dest: '/home/{{ ansible_user }}/buscainstrumentos_scrapers'
        clone: yes
        update: yes

    - name: Generate locale
      locale_gen:
        name: es_ES.UTF-8
        state: present


    - name: Run Python scraper scripts (soundmarket)
      command: "python3 {{ item.script }}"
      args:
          chdir: "/home/{{ ansible_user }}/buscainstrumentos_scrapers/scrapers"
      async: 18000
      poll: 5
      register: python_scraper_job
      when: item.category == category and item.website == 'soundmarket'
      with_items:
        - { category: 'guitar', website: 'soundmarket', script: 'soundmarketScrap_guitar.py' }
        - { category: 'bass', website: 'soundmarket', script: 'soundmarketScrap_bass.py' }
        - { category: 'drums', website: 'soundmarket', script: 'soundmarketScrap_drums.py' }
        - { category: 'keys', website: 'soundmarket', script: 'soundmarketScrap_keys.py' }


    - name: Run Python scraper scripts (reverbScrap.py)
      command: "python3 {{ item.script }}"
      args:
        chdir: "/home/{{ ansible_user }}/buscainstrumentos_scrapers/scrapers"
      async: 18000
      poll: 5
      register: python_scraper_job
      when: item.category == category and item.website == 'reverb'
      with_items:
        - { category: 'guitar', website: 'reverb', script: 'reverbScrap_guitar.py' }
        - { category: 'bass', website: 'reverb', script: 'reverbScrap_bass.py' }
        - { category: 'drums', website: 'reverb', script: 'reverbScrap_drums.py' }
        - { category: 'keys', website: 'reverb', script: 'reverbScrap_keys.py' }


    - name: Run Scrapy scraper scripts (hispasonic)
      shell: "scrapy runspider {{ item.script }} -o {{ item.output }}"
      args:
        chdir: "/home/{{ ansible_user }}/buscainstrumentos_scrapers/scrapers"
      async: 18000
      poll: 5
      register: scrapy_scraper_jobs
      when: item.category == category and item.website == 'hispasonic'
      loop:
        - { category: 'guitar', website: 'hispasonic', script: 'hispasonicScrap_guitar.py', output: 'hispasonic.csv' }
        - { category: 'bass', website: 'hispasonic', script: 'hispasonicScrap_bass.py', output: 'hispasonic.csv' }
        - { category: 'drums', website: 'hispasonic', script: 'hispasonicScrap_drums.py', output: 'hispasonic.csv' }
        - { category: 'keys', website: 'hispasonic', script: 'hispasonicScrap_keys.py', output: 'hispasonic.csv' }


    - name: Run Scrapy scraper scripts (guitarristas)
      shell: "scrapy runspider {{ item.script }} -o {{ item.output }}"
      args:
        chdir: "/home/{{ ansible_user }}/buscainstrumentos_scrapers/scrapers"
      async: 18000
      poll: 5
      register: scrapy_scraper_jobs
      when: item.category == category and item.website == 'guitarristas'
      loop:
        - { category: 'guitar', website: 'guitarristas', script: 'guitarristasScrap_guitar.py', output: 'guitarristas.csv' }
        - { category: 'bass', website: 'guitarristas', script: 'guitarristasScrap_bass.py', output: 'guitarristas.csv' }
    

    - name: Run database loader scripts
      command: "python3 {{ item }}"
      args:
        chdir: '/home/{{ ansible_user }}/buscainstrumentos_scrapers/db_loaders'
      environment:
        DB_USER: "{{ lookup('env', 'DB_USER') }}"
        DB_PASS: "{{ lookup('env', 'DB_PASS') }}"
        DB_NAME: "{{ lookup('env', 'DB_NAME') }}"
        DB_HOST: "{{ lookup('env', 'DB_HOST') }}"
        DB_PORT: "{{ lookup('env', 'DB_PORT') }}"
      with_items:
        - 'db_load_guitarristas.py'
        - 'db_load_hispasonic.py'
        - 'db_load_reverb.py'
        - 'db_load_soundmarket.py'