name: Deploy and Run Scrapers

on: [push]

jobs:
  deploy-and-run:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 'latest'
          
      - name: Terraform Init and Apply
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: terraformFiles
        env:
          TF_VAR_do_token: ${{ secrets.DO_API_KEY }}

      - name: Get Droplet IP
        id: get-ip
        run: echo "::set-output name=droplet_ip::$(terraform output -raw droplet_ip)"

      - name: Setup SSH
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > keyfile.pem
          chmod 600 keyfile.pem
          
      - name: Setup Ansible Inventory
        run: |
          echo "[droplets]" > inventory
          echo "${{ steps.get-ip.outputs.droplet_ip }} ansible_user=root ansible_ssh_private_key_file=./keyfile.pem" >> inventory

      - name: Run Ansible Playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: 'path/to/your/playbook.yml'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          directory: 'optional-working-directory'
          options: 'additional ansible-playbook CLI arguments'
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          
      - name: Destroy Infrastructure
        if: always()
        run: terraform destroy -auto-approve
        env:
          TF_VAR_do_token: ${{ secrets.DO_API_KEY }}
